# Generated by Django 5.0.2 on 2024-03-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="username",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
