# Generated by Django 5.0.2 on 2024-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0002_passenger_username_alter_passenger_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
