# Generated by Django 5.0.3 on 2024-04-23 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0002_alter_ticket_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paymen_status",
            new_name="payment_status",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
