# Generated by Django 5.0.3 on 2024-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bus_ticketing_app",
            "0003_rename_paymen_status_payment_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
