# Generated by Django 5.0.2 on 2024-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0003_alter_passenger_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="username",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
