# Generated by Django 5.0.2 on 2024-03-09 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0004_alter_passenger_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="username",
        ),
    ]
