# Generated by Django 5.0.2 on 2024-03-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0005_remove_passenger_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
