# Generated by Django 5.0.3 on 2024-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0005_rename_passenger_id_ticket_passenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
