# Generated by Django 5.0.2 on 2024-03-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0006_alter_passenger_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("comfirm_password", models.CharField(max_length=255)),
            ],
        ),
    ]
