# Generated by Django 5.0.2 on 2024-03-13 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0008_customuser_delete_admin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
