# Generated by Django 5.0.2 on 2024-03-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_ticketing_app", "0009_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busroute",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="busroute",
            name="duration",
        ),
        migrations.AddField(
            model_name="busroute",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
